
export const DICTIONARY = {
  en: {
    dashboard: 'Dashboard',
    brandKits: 'Brand Kits',
    campaigns: 'Campaigns',
    generator: 'Campaign AI',
    strategicPlanner: 'Strategic Plan',
    settings: 'Settings',
    admin: 'Admin Panel',
    pricing: 'Pricing',
    login: 'Login',
    logout: 'Logout',
    createBrand: 'Create Brand Kit',
    generate: 'Generate Campaign',
    history: 'Campaign History',
    totalCampaigns: 'Total Campaigns',
    activeBrands: 'Active Brands',
    postsGenerated: 'Posts Generated',
    upgrade: 'Upgrade Plan',
    campaignTitle: 'Campaign Title',
    objective: 'Objective',
    audience: 'Target Audience',
    brand: 'Brand',
    language: 'Language',
    generating: 'AI is crafting your campaign...',
    posts: 'Social Media Posts',
    stories: 'Instagram Stories',
    reels: 'Reels Scripts',
    caption: 'Caption',
    hashtags: 'Hashtags',
    cta: 'Call to Action',
    designNotes: 'Design Suggestion',
    admin_users: 'Manage Users',
    admin_plans: 'Manage Plans',
    admin_stats: 'Admin Overview',
    plan_name: 'Plan Name',
    price: 'Price',
    features: 'Features',
    status: 'Status',
    actions: 'Actions',
    limits_reached: 'Limits reached. Please upgrade your plan to create more.',
    generateStrategy: 'Build Strategy',
  },
  ar: {
    dashboard: 'لوحة القيادة',
    brandKits: 'هوية العلامة التجارية',
    campaigns: 'الحملات',
    generator: 'مولد الحملات بالذكاء الاصطناعي',
    strategicPlanner: 'الخطة الاستراتيجية',
    settings: 'الإعدادات',
    admin: 'لوحة المسؤول',
    pricing: 'الأسعار',
    login: 'تسجيل الدخول',
    logout: 'تسجيل الخروج',
    createBrand: 'إنشاء هوية تجارية',
    generate: 'توليد حملة',
    history: 'سجل الحملات',
    totalCampaigns: 'إجمالي الحملات',
    activeBrands: 'العلامات التجارية النشطة',
    postsGenerated: 'المنشورات المولدة',
    upgrade: 'ترقية الخطة',
    campaignTitle: 'عنوان الحملة',
    objective: 'الهدف',
    audience: 'الجمهور المستهدف',
    brand: 'العلامة التجارية',
    language: 'اللغة',
    generating: 'الذكاء الاصطناعي يصمم حملتك...',
    posts: 'منشورات التواصل الاجتماعي',
    stories: 'ستوري انستجرام',
    reels: 'نصوص الريلز',
    caption: 'الوصف',
    hashtags: 'الهاشتاقات',
    cta: 'دعوة لاتخاذ إجراء',
    designNotes: 'اقتراح التصميم',
    admin_users: 'إدارة المستخدمين',
    admin_plans: 'إدارة الخطط',
    admin_stats: 'نظرة عامة للمسؤول',
    plan_name: 'اسم الخطة',
    price: 'السعر',
    features: 'المميزات',
    status: 'الحالة',
    actions: 'الإجراءات',
    limits_reached: 'تم الوصول إلى الحد المسموح. يرجى ترقية خطتك للمتابعة.',
    generateStrategy: 'بناء الاستراتيجية',
  }
};

export const INITIAL_PLANS = [
  {
    id: 'free',
    name: 'Free Starter',
    price_monthly: 0,
    price_yearly: 0,
    is_active: true,
    created_at: new Date().toISOString(),
    features: { brands_limit: 1, campaigns_limit: 2, exports_limit: 1, team_limit: 0 }
  },
  {
    id: 'pro',
    name: 'Pro Creator',
    price_monthly: 29,
    price_yearly: 290,
    is_active: true,
    created_at: new Date().toISOString(),
    features: { brands_limit: 5, campaigns_limit: 20, exports_limit: 50, team_limit: 3 }
  },
  {
    id: 'agency',
    name: 'Agency Elite',
    price_monthly: 99,
    price_yearly: 990,
    is_active: true,
    created_at: new Date().toISOString(),
    features: { brands_limit: 50, campaigns_limit: 200, exports_limit: 1000, team_limit: 20 }
  }
];
