
import React, { useState, useEffect } from 'react';
import { useAuth, useLanguage } from '../App';
import { mockDb } from '../services/mockDb';
import { generateStrategicPlan } from '../services/geminiService';
import { BrandKit, StrategicPlan } from '../types';
import { 
  Compass, Loader2, Target, Globe, ArrowRight, CheckCircle2, 
  TrendingUp, Users, AlertTriangle, Lightbulb, Map, Zap, Calendar, Download
} from 'lucide-react';

const StrategicPlanPage: React.FC = () => {
  const { user } = useAuth();
  const { t } = useLanguage();
  const [brands, setBrands] = useState<BrandKit[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [result, setResult] = useState<StrategicPlan | null>(null);

  const [formData, setFormData] = useState({
    brand_id: '',
    goals: '',
    targetRegion: 'Europe & USA'
  });

  useEffect(() => {
    if (user?.id) mockDb.getBrandKits(user.id).then(setBrands);
  }, [user]);

  const handleGenerate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!user || !formData.brand_id) return;

    setIsLoading(true);
    try {
      const brand = brands.find(b => b.id === formData.brand_id);
      if (!brand) throw new Error("Brand not found");

      const strategyData = await generateStrategicPlan(
        brand,
        formData.goals,
        formData.targetRegion
      );

      const newPlan: StrategicPlan = {
        id: crypto.randomUUID(),
        user_id: user.id,
        brand_id: formData.brand_id,
        title: `${brand.name} Strategic Plan 2025`,
        ...strategyData,
        created_at: new Date().toISOString()
      };

      await mockDb.saveStrategicPlan(newPlan);
      setResult(newPlan);
    } catch (err) {
      console.error("Strategy Generation Failed:", err);
      alert("Failed to build strategic plan. Please try again.");
    } finally {
      setIsLoading(false);
    }
  };

  if (result) {
    return (
      <div className="space-y-12 animate-in fade-in slide-in-from-bottom-4 duration-700">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-3xl font-bold text-slate-900">{result.title}</h2>
            <p className="text-slate-500 font-medium">Generated by Gemini AI Growth Strategist</p>
          </div>
          <div className="flex gap-4">
             <button onClick={() => setResult(null)} className="px-6 py-2.5 bg-slate-100 text-slate-600 rounded-xl font-bold hover:bg-slate-200">New Strategy</button>
             <button className="flex items-center gap-2 px-6 py-2.5 bg-indigo-600 text-white rounded-xl font-bold shadow-lg shadow-indigo-100 hover:bg-indigo-700">
                <Download className="w-4 h-4" /> Export Report
             </button>
          </div>
        </div>

        {/* SWOT Section */}
        <section className="space-y-6">
           <h3 className="text-xl font-black text-slate-900 uppercase tracking-tight flex items-center gap-2">
             <Zap className="w-6 h-6 text-yellow-500" /> SWOT Analysis
           </h3>
           <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
              <div className="p-6 bg-emerald-50 rounded-3xl border border-emerald-100 space-y-4">
                 <div className="flex items-center gap-2 font-bold text-emerald-700 uppercase tracking-widest text-xs">
                   <TrendingUp className="w-4 h-4" /> Strengths
                 </div>
                 <ul className="space-y-2 text-sm text-emerald-900/70 font-medium">
                    {result.swot.strengths.map((s, i) => <li key={i} className="flex gap-2"><span>•</span> {s}</li>)}
                 </ul>
              </div>
              <div className="p-6 bg-rose-50 rounded-3xl border border-rose-100 space-y-4">
                 <div className="flex items-center gap-2 font-bold text-rose-700 uppercase tracking-widest text-xs">
                   <AlertTriangle className="w-4 h-4" /> Weaknesses
                 </div>
                 <ul className="space-y-2 text-sm text-rose-900/70 font-medium">
                    {result.swot.weaknesses.map((s, i) => <li key={i} className="flex gap-2"><span>•</span> {s}</li>)}
                 </ul>
              </div>
              <div className="p-6 bg-sky-50 rounded-3xl border border-sky-100 space-y-4">
                 <div className="flex items-center gap-2 font-bold text-sky-700 uppercase tracking-widest text-xs">
                   <Lightbulb className="w-4 h-4" /> Opportunities
                 </div>
                 <ul className="space-y-2 text-sm text-sky-900/70 font-medium">
                    {result.swot.opportunities.map((s, i) => <li key={i} className="flex gap-2"><span>•</span> {s}</li>)}
                 </ul>
              </div>
              <div className="p-6 bg-amber-50 rounded-3xl border border-amber-100 space-y-4">
                 <div className="flex items-center gap-2 font-bold text-amber-700 uppercase tracking-widest text-xs">
                   <AlertTriangle className="w-4 h-4" /> Threats
                 </div>
                 <ul className="space-y-2 text-sm text-amber-900/70 font-medium">
                    {result.swot.threats.map((s, i) => <li key={i} className="flex gap-2"><span>•</span> {s}</li>)}
                 </ul>
              </div>
           </div>
        </section>

        {/* Audience & Roadmap */}
        <div className="grid lg:grid-cols-3 gap-12">
           <div className="lg:col-span-1 space-y-12">
              <section className="space-y-6">
                <h3 className="text-xl font-black text-slate-900 uppercase tracking-tight flex items-center gap-2">
                  <Users className="w-6 h-6 text-indigo-600" /> Key Personas
                </h3>
                {result.audience_personas.map((persona, i) => (
                  <div key={i} className="p-8 bg-white rounded-[32px] border border-slate-100 shadow-sm space-y-4 hover:shadow-xl transition-shadow">
                     <h4 className="font-bold text-xl text-slate-900">{persona.name}</h4>
                     <div className="space-y-2">
                        <p className="text-[10px] font-black uppercase text-slate-400">Pain Points</p>
                        <div className="flex flex-wrap gap-2">
                           {persona.pain_points.map((p, j) => <span key={j} className="px-3 py-1 bg-slate-100 rounded-full text-[10px] font-bold text-slate-600">{p}</span>)}
                        </div>
                     </div>
                     <div className="pt-4 border-t border-slate-50">
                        <p className="text-[10px] font-black uppercase text-indigo-600 mb-1">Winning Strategy</p>
                        <p className="text-sm text-slate-600 leading-relaxed font-medium italic">"{persona.ideal_solution}"</p>
                     </div>
                  </div>
                ))}
              </section>

              <section className="space-y-6">
                <h3 className="text-xl font-black text-slate-900 uppercase tracking-tight flex items-center gap-2">
                  <TrendingUp className="w-6 h-6 text-violet-600" /> Competitors
                </h3>
                <div className="space-y-4">
                   {result.competitors.map((comp, i) => (
                     <div key={i} className="p-6 bg-slate-900 rounded-3xl space-y-4 shadow-xl">
                        <h4 className="font-bold text-white text-lg">{comp.name}</h4>
                        <div className="grid grid-cols-2 gap-4">
                           <div className="space-y-1">
                              <p className="text-[8px] font-black text-emerald-400 uppercase tracking-widest">Advantage</p>
                              <p className="text-xs text-slate-400 leading-tight">{comp.advantage}</p>
                           </div>
                           <div className="space-y-1">
                              <p className="text-[8px] font-black text-rose-400 uppercase tracking-widest">Vulnerability</p>
                              <p className="text-xs text-slate-400 leading-tight">{comp.vulnerability}</p>
                           </div>
                        </div>
                     </div>
                   ))}
                </div>
              </section>
           </div>

           <div className="lg:col-span-2 space-y-6">
              <h3 className="text-xl font-black text-slate-900 uppercase tracking-tight flex items-center gap-2">
                <Calendar className="w-6 h-6 text-indigo-600" /> 12-Month Roadmap
              </h3>
              <div className="grid gap-4">
                 {result.roadmap.map((step, i) => (
                   <div key={i} className="group flex gap-6 p-6 bg-white rounded-3xl border border-slate-100 hover:border-indigo-200 transition-all hover:shadow-md">
                      <div className="w-16 h-16 rounded-2xl bg-indigo-50 flex flex-col items-center justify-center shrink-0 border border-indigo-100">
                         <span className="text-[10px] font-black uppercase text-indigo-600">Month</span>
                         <span className="text-xl font-black text-indigo-900 leading-none">{i + 1}</span>
                      </div>
                      <div className="flex-1 space-y-2">
                         <div className="flex items-center justify-between">
                            <h4 className="font-bold text-lg text-slate-900">{step.month}: {step.focus}</h4>
                            <div className="w-2 h-2 rounded-full bg-slate-100 group-hover:bg-indigo-500 transition-colors"></div>
                         </div>
                         <div className="flex flex-wrap gap-2">
                            {step.tasks.map((task, k) => (
                               <span key={k} className="flex items-center gap-1.5 px-3 py-1 bg-slate-50 rounded-lg text-xs font-bold text-slate-500 border border-slate-100">
                                 <CheckCircle2 className="w-3 h-3 text-emerald-500" /> {task}
                               </span>
                            ))}
                         </div>
                      </div>
                   </div>
                 ))}
              </div>
           </div>
        </div>
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto space-y-12 py-10">
      <div className="text-center space-y-4">
         <div className="inline-flex items-center gap-3 px-4 py-1.5 bg-indigo-50 text-indigo-600 rounded-full text-xs font-black uppercase tracking-widest">
            <Compass className="w-4 h-4" /> Global Market Positioning
         </div>
         <h2 className="text-4xl font-black text-slate-900 tracking-tight">Build Your Marketing Empire</h2>
         <p className="text-lg text-slate-500 max-w-xl mx-auto">
            Convert your brand identity into a 12-month growth strategy with AI-powered SWOT, competitor analysis, and audience mapping.
         </p>
      </div>

      <div className="bg-white rounded-[48px] shadow-2xl border border-slate-100 overflow-hidden relative">
        {isLoading && (
          <div className="absolute inset-0 bg-white/95 backdrop-blur-xl z-50 flex flex-col items-center justify-center p-12 text-center animate-in fade-in duration-500">
             <div className="relative w-24 h-24 mb-10">
                <div className="absolute inset-0 border-4 border-slate-100 rounded-full"></div>
                <div className="absolute inset-0 border-4 border-indigo-600 rounded-full border-t-transparent animate-spin"></div>
                <Compass className="absolute inset-0 m-auto w-10 h-10 text-indigo-600 animate-pulse" />
             </div>
             <h3 className="text-3xl font-black text-slate-900 mb-4 uppercase tracking-tight">Architecting Growth...</h3>
             <div className="max-w-sm space-y-4">
                <p className="text-slate-500 font-medium leading-relaxed">Gemini 3 Pro is simulating market conditions, analyzing competitors, and generating a roadmap tailored for your brand.</p>
                <div className="flex justify-center gap-2">
                   <div className="w-2 h-2 rounded-full bg-indigo-200 animate-bounce [animation-delay:-0.3s]"></div>
                   <div className="w-2 h-2 rounded-full bg-indigo-400 animate-bounce [animation-delay:-0.15s]"></div>
                   <div className="w-2 h-2 rounded-full bg-indigo-600 animate-bounce"></div>
                </div>
             </div>
          </div>
        )}

        <form onSubmit={handleGenerate} className="p-10 md:p-16 space-y-12">
           <div className="grid md:grid-cols-2 gap-10">
              <div className="space-y-4">
                 <label className="text-xs font-black text-slate-400 uppercase tracking-widest ml-1">Select Brand Identity</label>
                 <div className="relative">
                    <select required className="w-full pl-14 pr-7 py-5 bg-slate-50 border border-slate-200 rounded-3xl outline-none font-bold text-slate-900 appearance-none focus:ring-4 focus:ring-indigo-100 transition-all" value={formData.brand_id} onChange={e => setFormData({...formData, brand_id: e.target.value})}>
                      <option value="">Choose your brand...</option>
                      {brands.map(b => <option key={b.id} value={b.id}>{b.name}</option>)}
                    </select>
                    <div className="absolute left-5 top-1/2 -translate-y-1/2 w-8 h-8 rounded-lg bg-indigo-100 flex items-center justify-center text-indigo-600">
                       <Zap className="w-5 h-5" />
                    </div>
                 </div>
              </div>

              <div className="space-y-4">
                 <label className="text-xs font-black text-slate-400 uppercase tracking-widest ml-1">Target Region</label>
                 <div className="relative">
                    <input required className="w-full pl-14 pr-7 py-5 bg-slate-50 border border-slate-200 rounded-3xl outline-none font-bold text-slate-900 focus:ring-4 focus:ring-indigo-100 transition-all" placeholder="e.g. Europe, USA, GCC" value={formData.targetRegion} onChange={e => setFormData({...formData, targetRegion: e.target.value})} />
                    <div className="absolute left-5 top-1/2 -translate-y-1/2 w-8 h-8 rounded-lg bg-emerald-100 flex items-center justify-center text-emerald-600">
                       <Globe className="w-5 h-5" />
                    </div>
                 </div>
              </div>
           </div>

           <div className="space-y-4">
              <label className="text-xs font-black text-slate-400 uppercase tracking-widest ml-1">Key Business Goals</label>
              <div className="relative">
                 <textarea required className="w-full pl-14 pr-7 py-7 bg-slate-50 border border-slate-200 rounded-[40px] outline-none font-bold text-slate-900 min-h-[160px] resize-none focus:ring-4 focus:ring-indigo-100 transition-all" placeholder="e.g. Increase recurring revenue by 40%, penetrate the young adult segment, launch 3 new products." value={formData.goals} onChange={e => setFormData({...formData, goals: e.target.value})} />
                 <div className="absolute left-5 top-8 w-8 h-8 rounded-lg bg-violet-100 flex items-center justify-center text-violet-600">
                    <Target className="w-5 h-5" />
                 </div>
              </div>
           </div>

           <button disabled={isLoading || !formData.brand_id} type="submit" className="w-full bg-slate-900 text-white py-6 rounded-[32px] font-black text-2xl hover:bg-slate-800 transition-all shadow-2xl flex items-center justify-center gap-5 disabled:bg-slate-200 group overflow-hidden">
              <span className="relative z-10">{t('generateStrategy')}</span>
              <ArrowRight className="w-7 h-7 group-hover:translate-x-3 transition-transform relative z-10" />
           </button>
        </form>
      </div>
    </div>
  );
};

export default StrategicPlanPage;
